GEMINI_API_KEY="AIzaSyAZSmPpFtNfa0Vqu37qqd5IwRgWdH3QFAM"
EMAIL_HOST = "sandbox.smtp.mailtrap.io"
EMAIL_PORT = 2525
EMAIL_USER = "785463dd0dd731"
EMAIL_PASSWORD = "4ab7513b285950"
ADMIN_PASSWORD = "fixdent123"
